import { HttpStatus } from '@nestjs/common';

/** Stable, machine readable error codes returned to API consumers. */
export const APP_ERROR_CODES = [
  'VALIDATION_FAILED',
  'BAD_REQUEST',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',
  'PAYLOAD_TOO_LARGE',
  'RATE_LIMIT_EXCEEDED',
  'INTERNAL_SERVER_ERROR',
  'SERVICE_UNAVAILABLE',
  'INVALID_INTERNAL_API_KEY',
  'ADMIN_API_KEY_NOT_CONFIGURED',
  'CHALLENGE_ALREADY_INITIALIZED',
  'CHALLENGE_NOT_INITIALIZED',
  'CHALLENGE_LATE_BASELINE_CAPTURE',
  'PARTICIPANT_NOT_FOUND',
  'PARTICIPANT_NOT_INITIALIZED',
  'SYNCHRONIZATION_ALREADY_RUNNING',
  'STORAGE_UNAVAILABLE',
  'STORAGE_CORRUPTED',
  'STORAGE_SCHEMA_UNSUPPORTED',
  'UNSUPPORTED_PLATFORM',
  'RIOT_API_NOT_CONFIGURED',
  'RIOT_AUTHENTICATION_FAILED',
  'RIOT_RATE_LIMITED',
  'RIOT_ACCOUNT_NOT_FOUND',
  'RIOT_RESOURCE_NOT_FOUND',
  'RIOT_UNAVAILABLE',
  'RIOT_REQUEST_TIMEOUT',
  'RIOT_UNEXPECTED_RESPONSE',
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];

const HTTP_STATUS_ERROR_CODE: Readonly<Record<number, AppErrorCode>> = {
  [HttpStatus.BAD_REQUEST]: 'BAD_REQUEST',
  [HttpStatus.UNAUTHORIZED]: 'UNAUTHORIZED',
  [HttpStatus.FORBIDDEN]: 'FORBIDDEN',
  [HttpStatus.NOT_FOUND]: 'NOT_FOUND',
  [HttpStatus.CONFLICT]: 'CONFLICT',
  [HttpStatus.PAYLOAD_TOO_LARGE]: 'PAYLOAD_TOO_LARGE',
  [HttpStatus.TOO_MANY_REQUESTS]: 'RATE_LIMIT_EXCEEDED',
  [HttpStatus.INTERNAL_SERVER_ERROR]: 'INTERNAL_SERVER_ERROR',
  [HttpStatus.SERVICE_UNAVAILABLE]: 'SERVICE_UNAVAILABLE',
};

/** Fallback code for framework exceptions that carry no domain code. */
export function errorCodeForHttpStatus(status: number): AppErrorCode {
  return HTTP_STATUS_ERROR_CODE[status] ?? 'INTERNAL_SERVER_ERROR';
}
